rm  -rdf *info*
rm -rdf aiofiles/
rm -rdf bin/
rm -rdf click/
rm -rdf datasette/
rm -rdf dateutil/
rm -rdf h11/
rm -rdf hnswlib/
rm -rdf httptools/
rm -rdf hupper/
rm -rdf importlib_metadata/
rm -rdf include/
rm -rdf jinja2/
rm -rdf mangum/
rm -rdf markupsafe/
rm -rdf more_itertools/
rm -rdf numpy/
rm -rdf pandas/
rm -rdf pint/
rm -rdf pluggy/
rm -rdf pybind11/
rm -rdf pytz/
rm -rdf tests/
rm -rdf uvicorn/
rm -rdf uvloop/
rm -rdf websockets/
rm -rdf websockets/
rm -rdf hnswlib*
rm -rdf __pycache__/
rm six*py zipp*py typing_extensions*py click_def*py 